name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRESQL_USR: ${{ secrets.POSTGRESQL_USR }}
      POSTGRESQL_PSW: ${{ secrets.POSTGRESQL_PSW }}
      POSTGRESQL_DB: ${{ secrets.POSTGRESQL_DB }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover tests/

      - name: Run database migration (if necessary)
        run: |
          # Include your migration commands here if necessary, like:
          # flask db upgrade or python manage.py migrate
          echo "Running database migration"

      - name: Deploy to production (optional)
        run: |
          # Your deployment commands go here (e.g., pushing to server, AWS, etc.)
          echo "Deploying to production"
